### ISSUE TITLE
missing utility secure-forward-ca-generate

### ISSUE THREAD

**Issue by commanderrikker** [tagomoris/fluent-plugin-secure-forward#18]
The documentation for the plugin here on github references this utility:
```secure-forward-ca-generate /path/for/dir/of/certs "passphrase for private CA secret key"```

However I don't have that program when I install the plugin.  Where/how do I get this?  Or can you change the instructions to reference an outside utility?

**Comment by tagomoris** [comment]
@commanderrikker Hmm, I confirmed that fluent-plugin-secure-forward-0.3.2.gem includes `bin/secure-forward-ca-generate`.
Are you using v0.3.2? or didn't you rehash on your rbenv or so?

**Comment by commanderrikker** [comment]
Looks like I have the correct version:
```root@logserver:~# td-agent-gem list | less
...
fluent-plugin-secure-forward (0.3.2)
...```

I found the utility here.  It just wasn't in my path:
`/opt/td-agent/embedded/lib/ruby/gems/2.1.0/bin/secure-forward-ca-generate`

Thanks for the help.  Closing the issue.

**Comment by repeatedly** [comment]
> I found the utility here. It just wasn't in my path:

This is td-agent design to prevent unexpected command overwrite.

http://docs.fluentd.org/articles/faq#i-installed-td-agent-and-want-to-add-custom-plugins-how-do-i-do-it

**Comment by commanderrikker** [comment]
Thanks for the help.  Can you clarify one issue for me?  What value does 
'shared_key' take?  Am I just generating a random password?  Or do I 
need to use the ssh-keygen utility with something like:

ssh-keygen -t rsa -b 4096


Thanks,

Rick

**Comment by tagomoris** [comment]
It's a random password or something you want, not related with RSA nor TLS. 

iPhone$B$+$iAw?.(B

2015/06/16 2:14$B!"(BRick Chatham <notifications@github.com> $B$N%a%C%;!<%8(B:
