### ISSUE TITLE
fluentd dies when a connection is reset.

### ISSUE THREAD

**Issue by kumai** [tagomoris/fluent-plugin-secure-forward#22]
Hi,

`OpenSSL::Buffering#read_nonblock`(called at output_node.rb:314) raises `Errno::ECONNRESET` when a connection is reset by peer unexpectedly, and then fluentd dies. I think the `SystemCallError` should be rescued in `SecureForwardOutput::Node#connect`.

**Comment by tagomoris** [comment]
I've fixed it and released `v0.3.3dev2`.
@kumai Can you test it?

**Comment by kumai** [comment]
Thank you for your quick fix and it LGTM. But unfortunately I don't know how to reproduce the 'connection reset' error manually, so I think it's difficult to test the fix in our environment. sorry...

**Comment by tagomoris** [comment]
OK, once i close this issue.
Please reopen if you find any problems.
