### ISSUE TITLE
Could I set a backup log destination on a network failure?

### ISSUE THREAD

**Issue by cherrot** [tagomoris/fluent-plugin-secure-forward#23]
Consider a situation that all the fluentd aggregator (log receiver) were down, I wish my fluentd forwarder could write logs into a backup destination such as local log file. 
It seems that currently this plugin does not support `<secondary>`  config just like what the `out_forward` plugin does.  Is there a plan for this, or is there any other way to accomplish my requirement? 
Thanks!

**Comment by repeatedly** [comment]
> `<secondary>` is a feature of buffered output plugin

secure-forward is a buffered output plugin so `<secondary>` should work.
Did you hit the problem?

**Comment by cherrot** [comment]
My bad , I forgot to set [retry_limit](http://docs.fluentd.org/articles/out_forward#retrylimit-disableretrylimit). As a consequence, `fluentd` would not write to my `<secondary>` destination after 17 times retry (by default it would happen in 36 hours...) 
Thanks and sorry for bothering :)

**Comment by repeatedly** [comment]
np. If you want to cap the retry, `max_retry_wait` is also useful.
