### ISSUE TITLE
On CentOS 6.4 install old 0.0.2 version

### ISSUE THREAD

**Issue by dpgaspar** [tagomoris/fluent-plugin-secure-forward#50]
When installing on an CentOS6.4 it always install an old plugin version:

fluent-logger (0.5.1)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-kafka (0.3.1)
fluent-plugin-mongo (0.7.15)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (0.7.1)
fluent-plugin-scribe (0.10.14)
fluent-plugin-secure-forward (0.0.2)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)

Even after upgrading ruby to version 2.0.0

Do you have any ideas?

Thanks

**Comment by tagomoris** [comment]
Does it work?: `gem install fluent-plugin-secure-forward -v 0.4.3`

**Comment by dpgaspar** [comment]
It doesn't, but if i include the gem's for resolve-hostname and fluent-plugin-secure-forward it works.
You can close this, since this is probably an edge case, this OS has some weird specifics.

Thanks!
