### ISSUE TITLE
Make shared_key optional for output plugin

### ISSUE THREAD

**Issue by ewolinetz** [tagomoris/fluent-plugin-secure-forward#53]
If we want to be able to ship logs securely with this plugin to another log aggregator that may not be fluentd (e.g. logstash), we should be able to not provide a `shared_key` for authentication.

Logstash can use SSL communication, and it has a Fluent codec to interpret events sourced from Fluentd. However using this plugin we cannot ship to them given that `shared_key` is required and Logstash has no means of using a `shared_key`.

**Comment by tagomoris** [comment]
This plugin is not to transfer logs to logstash.
